version: '3'

services:
  frontend:
    container_name: s3browser-frontend
    build:
      context: ./frontend/s3-bucket-browser
    ports:
      - "${FRONTEND_PORT:-8081}:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: s3browser-backend
    build:
      context: ./backend
    expose:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    depends_on:
      - redis
    volumes:
      - ./backend/config.json:/app/config.json:ro
    environment:
      - REDIS_HOST=${REDIS_HOST:-s3browser-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
    networks:
      - app-network

  redis:
    container_name: s3browser-redis
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: 